### ISSUE TITLE
For the next version

### ISSUE THREAD

**Issue by andreymatin** [andreymatin/scss-mixins#7]
@mixin abs-center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

**Comment by andreymatin** [comment]
### background underline

```css
    background-image: linear-gradient($color, $color);
    background-size: 100% 15px;
    background-position: 0 calc(100% - 5px);
    background-repeat: no-repeat;
```

**Comment by andreymatin** [comment]
### profile photo thumbnail

```
  width: $width;
  height: $width;
  min-width: $width;
  flex-basis: $width;
```

**Comment by andreymatin** [comment]
### Padding for hash links
ref: https://css-tricks.com/hash-tag-links-padding/

```scss
  &:before {
    display: block;
    content: " ";
    margin-top: -285px;
    height: 285px;
    visibility: hidden;
    pointer-events: none;
  }
```
